### ISSUE TITLE
v 4.0 roadmap

### ISSUE THREAD

**Issue by arturbien** [arturbien/React95#210]
Let's have a discussion on how we could rebuild and improve our project for our next major release. Here are some things that come to my mind:

- [ ] rewritten in Typescript,
- [ ] styling: utilize CSS variables and get rid of styled-components,
- [ ] component names should match corresponding Windows 95 component names 
- [ ] color variable names should match corresponding Windows 95 color variable names

**Comment by WesSouza** [comment]
@arturbien I'd love to work on rewriting using TypeScript.

**Comment by arturbien** [comment]
@WesSouza that would be awesome. We can discuss details on our Slack channel if you want (link in the README)

**Comment by WesSouza** [comment]
> investiage if creating border styles with border-image is a better alternative than using pseudo elements

I worked on a similar set of 95-themed components and used the `border-image` approach:
https://github.com/WesSouza/Wes95/blob/main/src/ui/Themes.ts#L5-L15

The project stalled a while ago, but it still works on https://wes95.com.
